# .github/workflows/metrics.yml
name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Core Options
          user: Nalin7parihar
          template: classic
          theme: radical
          config_timezone: Asia/Kolkata
          config_animations: yes # Enable animations for a dynamic feel

          # Plugins
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_languages: yes
            plugin_languages_limit: 8
            plugin_languages_analysis_timeout: 15
          plugin_isocalendar: yes
            plugin_isocalendar_duration: half-year
          plugin_stars: yes # Add a section for starred repositories
            plugin_stars_limit: 4
          plugin_followup: yes # Show open issues and pull requests
